name: Release Please

on:
  push:
    branches: [main]

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs.release_created }}
      tag: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          pull-request-title-pattern: 'chore${scope}: release${component} v${version}'
          bump-minor-pre-major: true
          default-branch: main
          changelog-types: '[{"type":"feat","section":"Features"},{"type":"fix","section":"Bug Fixes"},{"type":"perf","section":"Performance Improvements"},{"type":"deps","section":"Dependencies"},{"type":"revert","section":"Reverts"},{"type":"docs","section":"Documentation"},{"type":"style","section":"Styles","hidden":true},{"type":"chore","section":"Miscellaneous Chores","hidden":true},{"type":"refactor","section":"Code Refactoring","hidden":false},{"type":"test","section":"Tests","hidden":true},{"type":"ci","section":"Continuous Integration","hidden":true}]'

  publish:
    name: Publish extension
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.released }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Package
        run: yarn package

      - name: Upload VSIX package asset
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./bin.vsix
          asset_name: bin-${{ needs.release-please.outputs.tag }}.vsix
          tag: ${{ needs.release-please.outputs.tag }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish on Visual Studio Marketplace
        id: vsm
        run: |
          yarn deploy-vsce --packagePath bin.vsix
          echo ::set-output name=runned::true
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish on Open VSX
        if: steps.vsm.outputs.runned
        run: yarn deploy-ovsx bin.vsix -p ${{ secrets.OVSX_PAT }}
